### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by TheBlackGhost77** [Metalloriff/BetterDiscordPlugins#42] opened 2019-04-25 14:06 UTC
so the autocorrector no matter what doesnt work for me i tried restarting downloading nothing happend please help.

**Comment by irockdude554** [comment] 2019-04-25 14:32
I’m having the same issue as well, seems like it started doing this today.

**Comment by Cronosus** [comment] 2019-04-25 15:15
well.. then i'm sure its caused by plugin.. some plugins just stopped working, but i not seen any update.. weird

**Comment by sniperwolfortiz** [comment] 2019-04-26 00:49
If you guys go to the support server a friend of mine made a fixed version of the plugin and i just now posted a pull request for the updated version of the plugin so it can be fixed asap.

**Comment by irockdude554** [comment] 2019-04-27 21:33
> If you guys go to the support server a friend of mine made a fixed version of the plugin and i just now posted a pull request for the updated version of the plugin so it can be fixed asap.

Where is it posted at in the discord server?

**Comment by l0c4lh057** [comment] 2019-05-01 17:36
fixed in [this pr](https://github.com/Metalloriff/BetterDiscordPlugins/pull/47), changed version number in [0be0408](https://github.com/Metalloriff/BetterDiscordPlugins/commit/0be0408853afd7ff7e353e628e096a6aac8438e9)

**Closed by l0c4lh057** 2019-05-01 17:36 UTC
